# permissions for end users to view ats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: at-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: uat
    app.kubernetes.io/part-of: uat
    app.kubernetes.io/managed-by: kustomize
  name: at-viewer-role
rules:
- apiGroups:
  - uat.jerseymec.dev
  resources:
  - ats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - uat.jerseymec.dev
  resources:
  - ats/status
  verbs:
  - get
